const shows = [
    {
        id: 'show-1',
        band: 'La Femme',
        img: './img/lafemmeMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-2',
        band: 'Agar Agar',
        img: './img/agaragarMini.png',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-3',
        band: 'L´emperatriz',
        img: './img/lemperatriceMini.jpg',
        date: '21/02/2023',
        eventTime: '21 hs',
        location: 'Luna Park',
    },
    {
        id: 'show-4',
        band: 'Lana del Rey',
        img: './img/lanaMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-5',
        band: 'Nine Inch Nails',
        img: './img/ninMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Luna Park',
    },
    {
        id: 'show-6',
        band: 'Beach House',
        img: './img/beachhouseMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-7',
        band: 'Cigarretes After Sex',
        img: './img/cigarretsMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-8',
        band: 'Peces Raros',
        img: './img/pecesrarosMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-9',
        band: 'Ibiza Pareo',
        img: './img/ibizapareoMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-10',
        band: 'Nicolas Jaar',
        img: './img/nicolasjaarMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-11',
        band: 'Chemical Brothers',
        img: './img/chemicalbrothersMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-12',
        band: 'Rihanna',
        img: './img/rihannaMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-13',
        band: 'Imagine Dragons',
        img: './img/imaginedragonsMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-14',
        band: 'Air',
        img: './img/AirMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-15',
        band: 'Muse',
        img: './img/MuseMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },
    {
        id: 'show-16',
        band: 'David Lynch',
        img: './img/davidlynchMini.jpg',
        date: '23/05/2023',
        eventTime: '21 hs',
        location: 'Complejo Art Media',
    },

]

export { shows };